@baseUrl = http://localhost:3004/api

###

# @name login
POST {{baseUrl}}/login/ HTTP/1.1
content-type: application/json

{
  "username": "jean_duj",
  "password": "test_pw"
}

###

# @name getNotificationForAUser
GET {{baseUrl}}/notifications?status=accepted
content-type:application/json
Authorization: Bearer {{login.response.body.token}}


###

# @name changeNotificationForAUser
PATCH {{baseUrl}}/notifications/6a0a2733b325a0cd32882c7b/
content-type:application/json
Authorization: Bearer {{login.response.body.token}}

{
  "status":"accepted"
}

###