@baseUrl = http://localhost:3004/api


###

# @name createNewUser
POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
  "username": "jean_duj",
  "firstName": "Jean",
  "lastName": "Dujardin",
  "email": "jean_duj@gmail.com",
  "password":"test_pw"
}

###

# @name login
POST {{baseUrl}}/login/ HTTP/1.1
content-type: application/json

{
  "username": "jean_duj",
  "password": "test_pw"
}

###

# @name getArtistBySearch
GET {{baseUrl}}/artists/search?q=pignon
content-type:application/json


###

# @name patchNewArtistToUser
PATCH {{baseUrl}}/users/me
content-type:application/json
Authorization: Bearer {{login.response.body.token}}

{
  "artistId": "69f82da15219d8d08fd0769d"
}

###