@baseUrl = http://localhost:3004/api

###
# @name createUser
POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
  "username":"bob_down",
  "firstName":"Robert",
  "lastName":"Downey",
  "email":"r.downey@gmail.com",
  "password":"test_pw"
}


###

# @name login
POST {{baseUrl}}/login/ HTTP/1.1
content-type: application/json

{
  "username": "zozo",
  "password": "test_pw"
}

### 

# @name newArtist
POST {{baseUrl}}/artists/ HTTP/1.1
content-type:application/json
Authorization: Bearer {{login.response.body.token}}

{
  "firstName":"Aristide",
  "lastName":"Bruand",
  "dateOfBirth": "2005-01-15"
}

### 

# @name getAll
GET {{baseUrl}}/artists?limit=5 HTTP/1.1
content-type:application/json

###

# @name getAllPage2
GET {{baseUrl}}/artists?limit=5&cursor=eyJmaXJzdE5hbWUiOiJPcGjDqWxpZSIsImxhc3ROYW1lIjoiSm9iaW4iLCJfaWQiOiI2OWY4MzQ0MzYxN2Y3ZGNhMzM3MTMzMmQifQ HTTP/1.1
content-type:application/json

###

# @name getArtistBySearch
GET {{baseUrl}}/artists/search?q=fran
content-type:application/json

### 

# @name getArtistMe
GET {{baseUrl}}/artists/me HTTP/1.1
content-type:application/json
Authorization: Bearer {{login.response.body.token}}

###

# @name getPlaysByArtistId
GET {{baseUrl}}/artists/69f82e375219d8d08fd0769e/plays
content-type:application/json

###

# @name getArtistById
GET {{baseUrl}}/artists/69f82e375219d8d08fd0769e HTTP/1.1
content-type:application/json

###

# @name linkArtistUser
PATCH {{baseUrl}}/users/me HTTP/1.1
content-type:application/json
Authorization: Bearer {{login.response.body.token}}

{
  "artistId":"69f82e375219d8d08fd0769e",
  "username":"zozo",
  "firstName": "L'asticot",
  "lastName": "Toumou",
  "email":"zozolasticot@gmail.com"
}

###


